[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [
    { access = "read-write", path = "./script/target/" },
    { access = "read-write", path = "./broadcast/" },
    { access = "read-write", path = "./reports/" },
    { access = "read-write", path = "./signature.txt" },
]

remappings = ["@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"]
# ,"@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts"

[invariant]
runs = 92
depth = 20
fail_on_revert = true
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
